name: Run Tests and Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: lucasnpinheiro/php-fpm:php8.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy .env.example to .env
      run: |
        cp .env.example .env

    - name: Run tests
      run: |
        make test