name: Run Tests and Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t lucasnpinheiro:latest .
      working-directory: ./Dockerfile

    - name: Run tests
      run: make test
